FYP/FYP/FYP/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lpr/', include('LPR.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='lpr/', permanent=True)),
]

# For static files like CSS, JS, image
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# For media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FYP/FYP/LPR/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

#Important: The generic class-based detail view expects to be passed a parameter named pk. 
# If you're writing your own function view you can use whatever parameter name you like, 
# or indeed pass the information in an unnamed argument.

urlpatterns = [
    path('', views.index, name='index'),
    path('VehiclesIndex/', views.VehiclesIndex, name='VehiclesIndex'),
    path('analysis/', views.analysis, name='analysis'),
    path('recognition/', views.recognition, name='recognition'),
    path('vehicleExit/', views.vehicleExit, name='vehicleExit'),
    path('ownerEnter/', views.ownerEnter, name='ownerEnter'),
    path('visitorEnter/', views.visitorEnter, name='visitorEnter'),
    path('owners/', views.OwnerListView.as_view(), name='owners'),
    path('owner/<int:pk>', views.OwnerDetailView.as_view(), name='owner-detail'),
    path('owner/create/', views.OwnerCreate.as_view(), name='owner-create'),
    path('owner/<int:pk>/update/', views.OwnerUpdate.as_view(), name='owner-update'),
    path('owner/<int:pk>/delete', views.OwnerDelete.as_view(), name='owner-delete'),
    path('visitors/', views.VisitorListView.as_view(), name="visitors"),
    path('visitor/<int:pk>', views.VisitorDetailView.as_view(), name="visitor-detail"),
    path('visitor/create/', views.VisitorCreate.as_view(), name='visitor-create'),
    path('visitor/<int:pk>/update/', views.VisitorUpdate.as_view(), name='visitor-update'),
    path('visitor/<int:pk>/delete', views.VisitorDelete.as_view(), name='visitor-delete'),
    path('vehicles/', views.VehicleListView.as_view(), name="vehicles"),
    path('vehicle/<int:pk>', views.VehicleDetailView.as_view(), name="vehicle-detail"),
    path('vehicle/<int:pk>/create/', views.VehicleCreate.as_view(), name='vehicle-create'),
    path('vehicle/<int:pk>/update/', views.VehicleUpdate.as_view(), name='vehicle-update'),
    path('vehicle/<int:pk>/delete', views.VehicleDelete.as_view(), name='vehicle-delete'),
    path('recognitionEnterForm/', views.recognitionEnterForm, name="recognitionEnterForm"),
    path('recognitionExitForm/', views.recognitionExitForm, name="recognitionExitForm"),
]

# For static files like CSS, JS, image
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# For media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FYP/FYP/LPR/models.py
from django.urls import reverse
from django.db import models
from django.core.validators import RegexValidator
from django_resized import ResizedImageField

nameValidator = RegexValidator("^[a-zA-Z ]+$", "Name must only contain characters")
unitValidator = RegexValidator("^\d-\d{1,2}-\d$", "Unit number must match X-XX-X where X is number")
plateNumValidator = RegexValidator("^[A-Z]{1,3}[0-9]{1,4}[A-Za-z]{0,2}$", "License Plate Number should follow the format (PPP1234) no spaces required")

# Create your models here.
class Owner(models.Model):
    """Model representing owners"""
    name = models.CharField(max_length=100, help_text="Enter Resident's name (e.g. Tan Soon Lee)", validators=[nameValidator])
    unit = models.CharField(max_length=10, help_text="Enter Resident's unit number (e.g. 2-12-1)", validators=[unitValidator])

    # Sort by unit
    class Meta:
        ordering = ['unit']

    def __str__(self):
        """String for representing the Model object"""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a particular owner instance"""
        return reverse('owner-detail', args=[str(self.id)])


class Vehicle(models.Model):
    """Model representing Vehicle"""
    brand = models.CharField(max_length=50, help_text="Enter vehicle's brand (e.g. Honda)")
    model = models.CharField(max_length=50, help_text="Enter vehicle's model (e.g. Civic)")
    colour = models.CharField(max_length=20, help_text="Enter vehicle colour (e.g. Blue)")
    plateNum = models.CharField('License Plate Number', max_length=10, help_text="Enter license plate number (e.g. PPP1234)", unique=True, validators=[plateNumValidator])
    owner = models.ForeignKey('Owner', on_delete=models.CASCADE)

    class Meta:
        ordering = ['brand']

    def __str__(self):
        """String for representing the Model object"""
        return f'{self.brand} {self.model}'

    def get_absolute_url(self):
        """Returns the url to access a detail record for this vehicle"""
        return reverse('vehicle-detail', args=[str(self.id)])

class OwnerEnterDateTime(models.Model):
    """Model representing owner vehicle enter date time"""
    dateTime = models.DateTimeField()
    vehicle = models.ForeignKey('Vehicle', on_delete=models.CASCADE)

    def __str__(self):
        """String for representing the Model object"""
        return f'{self.vehicle.plateNum}'

class VisitorEnterDateTime(models.Model):
    """Model representing owner vehicle enter date time"""
    dateTime = models.DateTimeField(auto_now_add=True, blank=True)
    exitDateTime = models.DateTimeField(blank=True, null=True)
    visitor = models.ForeignKey('Visitor', on_delete=models.CASCADE)
    Balance = models.DecimalField(max_digits=100, decimal_places=2,default=0.00)


    def __str__(self):
        """String for representing the Model object"""
        return f'{self.visitor.visitorPlateNum}'

class Visitor(models.Model):
    """Model representing Visitors"""
    name = models.CharField(max_length=100, help_text="Enter name (e.g. Tan Ah Lee)", validators=[nameValidator])
    visitUnit = models.CharField('Visited Unit', max_length=10, help_text="Enter visited unit (e.g. 2-14-2)", validators=[unitValidator])
    email = models.EmailField('Email',max_length=254,help_text="Enter Your Email",default='')
    visitorPlateNum = models.CharField('License Plate Number', max_length=10, help_text="Enter vehicle's license plate number (e.g. PPP1234)", unique=True, validators=[plateNumValidator])

    class Meta:
        ordering = ['visitUnit']

    def __str__(self):
        """String for representing the Model object"""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this vehicle"""
        return reverse('visitor-detail', args=[str(self.id)])

class Image(models.Model):
    image = ResizedImageField(size=[200,200], upload_to='images', force_format = 'png')

FYP/FYP/LPR/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UploadForm(forms.Form):
    file = forms.FileField(widget=forms.FileInput(attrs={
        'id': 'file_id'
    }))

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username","email","password1","password2")

    def save(self,commit=True):
        user = super(NewUserForm,self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

FYP/FYP/LPR/views.py
import base64
import os
import time
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot as plt
from django.utils import timezone
from datetime import datetime
from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib import messages
from django.forms.models import ModelForm
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from rest_framework.exceptions import APIException, ValidationError
from .models import Owner, Vehicle, Visitor, Image, VisitorEnterDateTime, OwnerEnterDateTime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.files.storage import FileSystemStorage
# Webcam
from django.core.files import File
from django.core.files.base import ContentFile
from django.core.files.temp import NamedTemporaryFile
from urllib.request import urlopen
# OpenCV
import cv2
import imutils
import numpy as np
import random
import math


@login_required
def index(request):
    """Home Page"""
    return render(request, 'index.html')

@login_required
def VehiclesIndex(request):

    return render(request, 'VehiclesIndex.html')

@login_required
def analysis(request):

    balance = VisitorEnterDateTime.objects.values("Balance")
    quarter1=0
    quarter2=0
    quarter3=0
    quarter4=0
    for balances in balance:
        for fee in balances.values():
            print(fee)
            if fee >60:
                quarter4+=1
            elif fee >=30:
                quarter3+=1
            elif fee >=10:
                quarter2+=1
            elif fee >=0:
                quarter1+=1

    total=quarter4+quarter3+quarter2+quarter1

    labels = '<10s','10-30s','31-60s','>60s'
    sizes = [quarter1,quarter2,quarter3,quarter4]
    explode = (0,0,0,0)  # only "explode" the 2nd slice (i.e. 'Hogs')
    fig1, ax1 = plt.subplots()
    ax1.pie(sizes, explode=explode, labels=labels, autopct='%1.1f%%',
            shadow=True, startangle=90)
    ax1.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
    plt.savefig(r'C:\\Users\\PC\\Desktop\\FYP\\FYP\\LPR\\static\\images\\sale_purchase_peichart.png',dpi=100)

    context={

    "quarter1" : quarter1,
    "quarter2" : quarter2,
    "quarter3" : quarter3,
    "quarter4" : quarter4,
    "total" : total

    }

    return render(request, 'analysis.html',context=context)
    
@login_required
def recognition(request):
    now = datetime.now()
    context = dict()
    if request.method == 'POST':
        if request.POST["src"] != "":
            path = request.POST["src"] # src is from JS
            image = NamedTemporaryFile()
            image.write(urlopen(path).read())
            image.flush()
            image = File(image)
            name = now.strftime("%d%m%Y_%H%M%S")
            name += '.png'
            image.name = name
            if image is not None:
                obj = Image.objects.create(image=image) # create an image obj
                obj.save()
                context["image_path"] = obj.image.url
                
            else:
                return redirect('/')

            frame = cv2.imread(get_image_file(name))

            imgToDisplay, licPlateChar = toRun(frame)
        
            bw_frame_buff = cv2.imencode('.jpg', imgToDisplay)[1].tobytes()
            bw_frame_b64 = base64.b64encode(bw_frame_buff)
            bw_frame_64_latest = bw_frame_b64.decode("utf-8")
            context["img"] = bw_frame_64_latest
            if licPlateChar == "Nothing":      
                context["plateNum"] = "Nothing"
            else:       
                context["plateNum"] = licPlateChar.strChars

            sameCurrentPlateNum = Vehicle.objects.filter(plateNum=context["plateNum"])
            sameVisitorPlateNum = Visitor.objects.filter(visitorPlateNum=context["plateNum"])

            if sameCurrentPlateNum.exists():   
                ownerId = sameCurrentPlateNum[0].id
                owner = Vehicle.objects.get(id = ownerId)
                context["vehicleName"] = owner
                context["ownerName"] = owner.owner.name
                context["ownerUnit"] = owner.owner.unit
                context["vehicleColour"] = owner.colour
                obj = OwnerEnterDateTime.objects.create(dateTime = datetime.now(), vehicle=owner)
                obj.save()
                os.remove(get_image_file(name))
                Image.objects.all().delete()

            elif sameVisitorPlateNum.exists():
                visitorId = sameVisitorPlateNum[0].id
                visitor = Visitor.objects.get(id = visitorId)
                context["visitorName"] = visitor.name
                context["visitUnit"] = visitor.visitUnit
                context["visitorPlateNum"] = visitor.visitorPlateNum
                obj = VisitorEnterDateTime.objects.create(dateTime = datetime.now(), visitor=visitor)
                obj.save()
                os.remove(get_image_file(name))
                Image.objects.all().delete()

            else:
                context["notFound"] = "Vehicle is not found in database, please proceed to management office to add details."
                os.remove(get_image_file(name))
                Image.objects.all().delete()

        else:
            context["errorMsg"] = "Please click 'Take Photo' button first before clicking 'Submit' button"
            
    return render(request, 'recognition.html', context=context)

@login_required
def vehicleExit(request):
    context = dict()
    now = datetime.now()
    if request.method == 'POST':
        if request.POST["src"] != "":
            path = request.POST["src"] # src is from JS
            image = NamedTemporaryFile()
            image.write(urlopen(path).read())
            image.flush()
            image = File(image)
            name = now.strftime("%d%m%Y_%H%M%S")
            name += '.png'
            image.name = name
            if image is not None:
                obj = Image.objects.create(image=image) # create an image obj
                obj.save()
                context["image_path"] = obj.image.url
                
            else:
                return redirect('/')

            frame = cv2.imread(get_image_file(name))

            imgToDisplay, licPlateChar = toRun(frame)
        
            bw_frame_buff = cv2.imencode('.jpg', imgToDisplay)[1].tobytes()
            bw_frame_b64 = base64.b64encode(bw_frame_buff)
            bw_frame_64_latest = bw_frame_b64.decode("utf-8")
            context["img"] = bw_frame_64_latest
            if licPlateChar == "Nothing":      
                context["plateNum"] = "Nothing"
            else:       
                context["plateNum"] = licPlateChar.strChars

            sameCurrentPlateNum = Vehicle.objects.filter(plateNum=context["plateNum"])
            sameVisitorPlateNum = Visitor.objects.filter(visitorPlateNum=context["plateNum"])

            if sameCurrentPlateNum.exists():   
                ownerId = sameCurrentPlateNum[0].id
                owner = Vehicle.objects.get(id = ownerId)
                context["vehicleName"] = owner
                context["ownerName"] = owner.owner.name
                context["ownerUnit"] = owner.owner.unit
                context["vehicleColour"] = owner.colour
                os.remove(get_image_file(name))
                Image.objects.all().delete()

            elif sameVisitorPlateNum.exists():
                visitorId = sameVisitorPlateNum[0].id
                visitor = Visitor.objects.get(id = visitorId)


                context["visitorName"] = visitor.name
                context["visitUnit"] = visitor.visitUnit
                context["visitorPlateNum"] = visitor.visitorPlateNum

                getExitObj = VisitorEnterDateTime.objects.filter(visitor=visitor).latest('dateTime')
                context["enterDateTime"] = getExitObj.dateTime
                


                getExitObj.exitDateTime = now
                getExitObj.save()
                os.remove(get_image_file(name))
                Image.objects.all().delete()

            else:
                context["notFound"] = "Vehicle is not found in database, please proceed to management office to add details."
                os.remove(get_image_file(name))
                Image.objects.all().delete()

        else:
            context["errorMsg"] = "Please click 'Take Photo' button first before clicking 'Submit' button"
    return render(request, 'vehicleExit.html', context=context)

@login_required
def recognitionExitForm(request):
    now = datetime.now()
    context = dict()
    if request.method == 'POST' and request.FILES['upload']:
        upload = request.FILES['upload']
        fss = FileSystemStorage(location=r'C:\Users\PC\Desktop\FYP\FYP\media\images')
        file = fss.save(upload.name, upload)
        if file is not None:
            obj = Image.objects.create(image=file) # create an image obj
            obj.save()
            context["image_path"] = obj.image.url
            
        else:
            return redirect('/')

        frame = cv2.imread(get_image_file(file))

        imgToDisplay, licPlateChar = toRun(frame)
    
        bw_frame_buff = cv2.imencode('.jpg', imgToDisplay)[1].tobytes()
        bw_frame_b64 = base64.b64encode(bw_frame_buff)
        bw_frame_64_latest = bw_frame_b64.decode("utf-8")
        context["img"] = bw_frame_64_latest
        if licPlateChar == "Nothing":      
            context["plateNum"] = "Nothing"
        else:       
            context["plateNum"] = licPlateChar.strChars

        sameCurrentPlateNum = Vehicle.objects.filter(plateNum=context["plateNum"])
        sameVisitorPlateNum = Visitor.objects.filter(visitorPlateNum=context["plateNum"])

        if sameCurrentPlateNum.exists():   
            ownerId = sameCurrentPlateNum[0].id

FYP/FYP/LPR/templates/LPR/owner_confirm_delete.html
{% extends "base_generic.html" %}
{% block title %}
    <title>Resident Delete</title>
{% endblock %}
{% block content %}
<div class="center-div">
  <h1 style="text-align:center;">Delete Resident</h1>
  <p>Are you sure you want to delete the resident: {{ owner }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <a href="{% url 'owner-detail' owner.id %}"><input type="button" class="addBtn" value="No, please take me back"></a>
    <input type="submit" class="deleteBtn" value="Yes, delete">
    
  </form>
</div>
{% endblock %}

FYP/FYP/LPR/templates/LPR/owner_detail.html
{% extends "base_generic.html" %}
{% block title %}
    <title>Resident Details</title>
{% endblock %}
{% block content %}
<div class="center-div">
  <h1>Resident Details</h1>
  <hr>
  <p><strong>Name:</strong> {{ owner.name }}</p>
  <p><strong>Unit:</strong> {{ owner.unit }}</p>

  <a href="{% url 'owner-update' owner.id %}"><input type="button" class="editBtn" value="Edit"></a>
  <a href="{% url 'owner-delete' owner.id %}"><input type="button" class="deleteBtn" value="Delete"></a>
  <a href="{% url 'vehicle-create' owner.id %}"><input type="button" class="addBtn" value="Add Vehicle"></a>

  <div style="margin-left:20px;margin-top:20px">
    <h2>Vehicles</h4>
    {% if owner.vehicle_set.all %}
      {% for vehicles in owner.vehicle_set.all %}
        <hr>
        <p>
          <a href="{% url 'vehicle-detail' vehicles.id %}">{{ vehicles.brand }} {{ vehicles.model }}</a>
        </p>
      {% endfor %}
    {% else %}
      <hr>
      <strong><p>There is no vehicle associate to this resident.</p></strong>
    {% endif %}
  </div>
</div>
{% endblock %}

FYP/FYP/LPR/templates/LPR/owner_form.html
{% extends "base_generic.html" %}
{% block title %}
  {% if 'create' in request.path %}
    <title>Create A Resident</title>
  {% elif 'update' in request.path %}
    <title>Edit A Resident</title>
  {% endif %}
{% endblock %}
{% block content %}

<div class="center-div">
  {% if 'create' in request.path %}
  <h1 style="text-align:center;">Create A Resident</h1>
  {% elif 'update' in request.path %}
  <h1 style="text-align:center;">Edit A Resident</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table style="margin: 0 auto; margin-top: 40px;">
    {{ form.as_table }}
    </table>
    <input type="submit" style="margin-top:20px;" class="editBtn" value="Submit">
  </form>
</div>
{% endblock %}

FYP/FYP/LPR/templates/LPR/owner_list.html
{% extends "base_generic.html" %}
{% block title %}
    <title>Resident List</title>
{% endblock %}
{% block content %}
  <h1 style="text-align:center;">Resident List</h1>
  
  {% if owner_list %}
  <table class="owner-enter-table">
    <tr>
        <th>Resident Name</th>
        <th>Unit</th>
        <th></th>
        <th></th>
    </tr>
    {% for owner in owner_list %}
    <tr>
        <td>{{ owner }}</td>
        <td>{{ owner.unit }}</td>
        <td><a href="{{ owner.get_absolute_url }}"><input type="button" class="addBtn" value="View"></a></td>
        <td><a href="{% url 'owner-delete' owner.id %}"><input type="button" class="deleteBtn" value="DELETE"></a></td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
    <p>There are no resident in the system.</p>
  {% endif %}
{% endblock %}

FYP/FYP/LPR/templates/LPR/vehicle_confirm_delete.html
{% extends "base_generic.html" %}
{% block title %}
    <title>Vehicle Delete</title>
{% endblock %}
{% block content %}
<div class="center-div">
  <h1 style="text-align:center;">Delete Vehicle</h1>

  <p>Are you sure you want to delete the vehicle: {{ vehicle }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <a href="{% url 'vehicle-detail' vehicle.id %}"><input type="button" class="addBtn" value="No, please take me back"></a>
    <input type="submit" class="deleteBtn" value="Yes, delete">
  </form>
</div>
{% endblock %}

FYP/FYP/LPR/templates/LPR/vehicle_detail.html
{% extends "base_generic.html" %}
{% block title %}
    <title>Vehicle Details</title>
{% endblock %}
{% block content %}
<div class="center-div">
  <h1>Vehicle Details</h1>
  <hr>
  <p><strong>Brand:</strong> {{ vehicle.brand }}</p>
  <p><strong>Model:</strong> {{ vehicle.model }}</p>
  <p><strong>Colour:</strong> {{ vehicle.colour }}</p>
  <p><strong>License Plate Number:</strong> {{ vehicle.plateNum }}</p>
  <p><strong>Owner:</strong> {{ vehicle.owner.name }}</p>

  <a href="{% url 'vehicle-update' vehicle.id %}"><input type="button" class="editBtn" value="Edit"></a>
  <a href="{% url 'vehicle-delete' vehicle.id %}"><input type="button" class="deleteBtn" value="Delete"></a>
</div>
{% endblock %}

FYP/FYP/LPR/templates/LPR/vehicle_form.html
{% extends "base_generic.html" %}

{% block title %}
  {% if 'create' in request.path %}
    <title>Create A Vehicle</title>
  {% elif 'update' in request.path %}
    <title>Edit A Vehicle</title>
  {% endif %}
{% endblock %}

{% block content %}
<div class="center-div">
  {% if 'create' in request.path %}
  <h1 style="text-align:center;">Create A Vehicle</h1>
  {% elif 'update' in request.path %}
  <h1 style="text-align:center;">Edit A Vehicle</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table style="margin: 0 auto; margin-top: 40px;">
    {{ form.as_table }}
    </table>
    <input type="submit" style="margin-top:20px;" class="editBtn" value="Submit">
  </form>
</div>
{% endblock %}

FYP/FYP/LPR/templates/LPR/vehicle_list.html
{% extends "base_generic.html" %}
{% block title %}
    <title>Vehicle List</title>
{% endblock %}
{% block content %}
  <h1 style="text-align:center;">Vehicle List</h1>
  {% if vehicle_list %}
  <table class="owner-enter-table">
    <tr>
        <th>Name</th>
        <th>Plate Number</th>
        <th>Owner name</th>
        <th></th>
        <th></th>
    </tr>
    {% for vehicle in vehicle_list %}
    <tr>
        <td>{{ vehicle }}</td>
        <td>{{ vehicle.plateNum }}</td>
        <td>{{ vehicle.owner }}</td>
        <td><a href="{{ vehicle.get_absolute_url }}" style="text-decoration:none;"><input type="button" class="addBtn" value="View"></a></td>
        <td><a href="{% url 'vehicle-delete' vehicle.id %}" style="text-decoration:none;"><input type="button" class="deleteBtn" value="DELETE"></a></td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
    <p>There are no vehicle in the system.</p>
  {% endif %}
{% endblock %}

FYP/FYP/LPR/templates/LPR/visitor_confirm_delete.html
{% extends "base_generic.html" %}
{% block title %}
    <title>Visitor Delete</title>
{% endblock %}
{% block content %}
<div class="center-div">
  <h1 style="text-align:center;">Delete Vehicles</h1>

  <p>Are you sure you want to delete the vehicles: {{ visitor.visitorPlateNum}}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <a href="{% url 'visitor-detail' visitor.id %}"><input type="button" class="addBtn" value="No, please take me back"></a>
    <input type="submit" class="deleteBtn" value="Yes, delete">
  </form>
</div>
{% endblock %}

FYP/FYP/LPR/templates/LPR/visitor_detail.html
{% extends "base_generic.html" %}
{% block title %}
    <title>Visitor Details</title>
{% endblock %}
{% block content %}
<div class="center-div">
  <h1>Vehicles Details</h1>
  <hr>
  <p><strong>Name:</strong> {{ visitor.name }}</p>
  <p><strong>Email:</strong> {{ visitor.email }}</p>
  <p><strong>License Plate Number:</strong> {{ visitor.visitorPlateNum }}</p> 

  <a href="{% url 'visitor-update' visitor.id %}"><input type="button" class="editBtn" value="Edit"></a>
  <a href="{% url 'visitor-delete' visitor.id %}"><input type="button" class="deleteBtn" value="Delete"></a>
</div>
{% endblock %}

FYP/FYP/LPR/templates/LPR/visitor_form.html
{% extends "base_generic.html" %}

{% block title %}
  {% if 'create' in request.path %}
    <title>Create A Visitor</title>
  {% elif 'update' in request.path %}
    <title>Edit A Visitor</title>
  {% endif %}
{% endblock %}

{% block content %}
<div class="center-div">
  {% if 'create' in request.path %}
  <h1 style="text-align:center;">Register a Vehicles</h1>
  {% elif 'update' in request.path %}
  <h1 style="text-align:center;">Edit A Vehicles</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table style="margin: 0 auto; margin-top: 40px;">
    {{ form.as_table }}
    </table>
    <input type="submit" style="margin-top:20px;" class="editBtn" value="Submit">
  </form>
</div>
{% endblock %}

FYP/FYP/LPR/templates/LPR/visitor_list.html
{% extends "base_generic.html" %}
{% block title %}
    <title>Visitor List</title>
{% endblock %}
{% block content %}
  <h1 style="text-align:center;">Vehicles List</h1>
  {% if visitor_list %}
  <table class="owner-enter-table">
    <tr>
        <th>Name</th>
        <th>Plate Number</th>
        <th>Email</th>
        <th></th>
        <th></th>
    </tr>
    {% for visitor in visitor_list %}
    <tr>
        <td>{{ visitor.name }}</td>
        <td>{{ visitor.visitorPlateNum }}</td>
        <td>{{ visitor.email}}</td>
        <td><a href="{{ visitor.get_absolute_url }}" style="text-decoration:none;"><input type="button" class="addBtn" value="View"></a></td>
        <td><a href="{% url 'visitor-delete' visitor.id %}" style="text-decoration:none;"><input type="button" class="deleteBtn" value="DELETE"></a></td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
    <p>There are no visitor in the system.</p>
  {% endif %}
{% endblock %}